export const GET_SINGLE_PRODUCTS_REQUEST = "GET_SINGLE_PRODUCTS_REQUEST";
export const GET_SINGLE_PRODUCTS_SUCCESS = "GET_SINGLE_PRODUCTS_SUCCESS";
export const GET_SINGLE_PRODUCTS_FAILURE = "GET_SINGLE_PRODUCTS_FAILURE";

export const POST_SINGLE_PRODUCTS_REQUEST = "POST_SINGLE_PRODUCTS_REQUEST";
export const POST_SINGLE_PRODUCTS_SUCCESS = "POST_SINGLE_PRODUCTS_SUCCESS";
export const POST_SINGLE_PRODUCTS_FAILURE = "POST_SINGLE_PRODUCTS_FAILURE";

export const DELETE_SINGLE_PRODUCTS_REQUEST = "DELETE_SINGLE_PRODUCTS_REQUEST";
export const DELETE_SINGLE_PRODUCTS_SUCCESS = "DELETE_SINGLE_PRODUCTS_SUCCESS";
export const DELETE_SINGLE_PRODUCTS_FAILURE = "DELETE_SINGLE_PRODUCTS_FAILURE";