export const SIGNUP_SIGNUP_REQUEST = "SIGNUP_SIGNUP_REQUEST"
export const SIGNUP_SIGNUP_SUCCESS = "SIGNUP_SIGNUP_SUCCESS"
export const SIGNUP_SIGNUP_FAILURE = "SIGNUP_SIGNUP_FAILURE"


export const LOGIN_SIGNUP_REQUEST = "LOGIN_SIGNUP_REQUEST"
export const LOGIN_SIGNUP_SUCCESS = "LOGIN_SIGNUP_SUCCESS"
export const LOGIN_SIGNUP_FAILURE = "LOGIN_SIGNUP_FAILURE"