
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const POST_CART_REQUEST = "POST_CART_REQUEST";
export const POST_CART_SUCCESS = "POST_CART_SUCCESS";
export const POST_CART_FAILURE = "POST_CART_FAILURE";

export const PATCH_CART_REQUEST = "PATCH_CART_REQUEST";
export const PATCH_CART_SUCCESS = "PATCH_CART_SUCCESS";
export const PATCH_CART_FAILURE = "PATCH_CART_FAILURE";

export const PUT_CART_REQUEST = "PUT_CART_REQUEST";
export const PUT_CART_SUCCESS = "PUT_CART_SUCCESS";
export const PUT_CART_FAILURE = "PUT_CART_FAILURE";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAILURE = "DELETE_CART_FAILURE";





