
export const GET_SHOPLATER_REQUEST = "GET_SHOPLATER_REQUEST";
export const GET_SHOPLATER_SUCCESS = "GET_SHOPLATER_SUCCESS";
export const GET_SHOPLATER_FAILURE = "GET_SHOPLATER_FAILURE";

export const POST_SHOPLATER_REQUEST = "POST_SHOPLATER_REQUEST";
export const POST_SHOPLATER_SUCCESS = "POST_SHOPLATER_SUCCESS";
export const POST_SHOPLATER_FAILURE = "POST_SHOPLATER_FAILURE";

export const PATCH_SHOPLATER_REQUEST = "PATCH_SHOPLATER_REQUEST";
export const PATCH_SHOPLATER_SUCCESS = "PATCH_SHOPLATER_SUCCESS";
export const PATCH_SHOPLATER_FAILURE = "PATCH_SHOPLATER_FAILURE";

export const PUT_SHOPLATER_REQUEST = "PUT_SHOPLATER_REQUEST";
export const PUT_SHOPLATER_SUCCESS = "PUT_SHOPLATER_SUCCESS";
export const PUT_SHOPLATER_FAILURE = "PUT_SHOPLATER_FAILURE";

export const DELETE_SHOPLATER_REQUEST = "DELETE_SHOPLATER_REQUEST";
export const DELETE_SHOPLATER_SUCCESS = "DELETE_SHOPLATER_SUCCESS";
export const DELETE_SHOPLATER_FAILURE = "DELETE_SHOPLATER_FAILURE";





